import type { Product } from "./types"

export const mockProducts: Product[] = [
  {
    id: "1",
    name: "Idly Batter",
    category: "breakfast",
    price: 120,
    description: "Fresh homemade idly batter, ready to cook",
    image: "/idly-batter-container.jpg",
    inStock: true,
    tags: ["south-indian", "breakfast", "ready-to-cook"],
  },
  {
    id: "2",
    name: "Dosa Batter",
    category: "breakfast",
    price: 150,
    description: "Premium dosa batter for crispy dosas",
    image: "/dosa-batter-container.jpg",
    inStock: true,
    tags: ["south-indian", "breakfast", "ready-to-cook"],
  },
  {
    id: "3",
    name: "Coconut Chutney",
    category: "condiments",
    price: 80,
    description: "Fresh coconut chutney, perfect with idly and dosa",
    image: "/coconut-chutney-bowl.jpg",
    inStock: true,
    tags: ["south-indian", "condiments", "fresh"],
  },
  {
    id: "4",
    name: "Rasam Powder",
    category: "spices",
    price: 200,
    description: "Authentic rasam powder blend",
    image: "/rasam-powder-spice-jar.jpg",
    inStock: true,
    tags: ["spices", "south-indian", "powder"],
  },
  {
    id: "5",
    name: "Sambar Mix",
    category: "ready-to-eat",
    price: 180,
    description: "Ready-to-eat sambar mix, just add water",
    image: "/sambar-mix-packet.jpg",
    inStock: false,
    tags: ["ready-to-eat", "south-indian", "instant"],
  },
  {
    id: "6",
    name: "Upma Mix",
    category: "breakfast",
    price: 90,
    description: "Instant upma mix for quick breakfast",
    image: "/upma-mix-packet.jpg",
    inStock: true,
    tags: ["breakfast", "instant", "south-indian"],
  },
  {
    id: "7",
    name: "Filter Coffee Powder",
    category: "beverages",
    price: 250,
    description: "Premium South Indian filter coffee powder",
    image: "/filter-coffee-powder-pack.jpg",
    inStock: true,
    tags: ["beverages", "coffee", "south-indian"],
  },
  {
    id: "8",
    name: "Ghee",
    category: "dairy",
    price: 450,
    description: "Pure cow ghee, 500ml",
    image: "/ghee-jar-golden.jpg",
    inStock: true,
    tags: ["dairy", "cooking", "pure"],
  },
]

export const categories = ["breakfast", "condiments", "spices", "ready-to-eat", "beverages", "dairy"]
